services:
  fragments:
    build: .
    environment:
      - PORT=8080
      - API_URL=http://localhost:8080
      - HTPASSWD_FILE=tests/.htpasswd
      - LOG_LEVEL=${LOG_LEVEL:-debug}

      - AWS_REGION=us-east-1
      - AWS_S3_ENDPOINT_URL=http://localstack:4566
      - AWS_DYNAMODB_ENDPOINT_URL=http://localstack:4566

      - AWS_S3_BUCKET_NAME=fragments
      - AWS_DYNAMODB_TABLE_NAME=fragments

      - AWS_ACCESS_KEY_ID=ASIA2UC27PXRVBWNCKJF
      - AWS_SECRET_ACCESS_KEY=HPUXU3Fh3+Cm7VtqO8F/dBLMGTelnFmhTqicQNxH

    ports:
      - '8080:8080'
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack_data # store LocalStack data here instead of /tmp/localstack
